### ISSUE TITLE
Has this incubation stalled?

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/reducing-memory-copies#3]
Not seeing any activity for a few years, so wondering if it's ok to archive this repository?

Unless I hear otherwise, I'll go ahead an archive this in a week or so.

**Comment by yoavweiss** [comment]
^^ @kenrussell

**Comment by tidoust** [comment]
That's a good question. The repository was more created as a discussion forum for cross-group coordination on memory copies than as a place to incubate solutions (and I don't think anyone expects a single platform-wide solution in that space).

The topic is still live in the sense that the impact of memory copies continues to be raised in groups, especially in media-related ones, and proper solutions continue to require cross-coordination between multiple groups, something that we're not always very good at.

I know I keep pointing people at this repository when they raise issues with memory copies that are hard to solve at the group level. It is fair to say that this has not triggered much activity though. Could you give me a few more months to figure out whether there is something useful that we could achieve here?

**Comment by annevk** [comment]
Yeah, it's unfortunate that issues raised did not end up being raised here. Because we really shouldn't be shipping the org-chart. If there's something missing in JavaScript for instance, that should be added there and not worked around.

**Comment by padenot** [comment]
Nothing to add to what @tidoust and @annevk have said, this needs work in ES and various WG for different Web APIs (At least the AudioWG and the Media WG, and probably WebGPU and others).

We need a place to keep discussions, point people to and discuss this, but I'm not sure where that would be.

**Comment by annevk** [comment]
I wonder if @littledan or @ljharb might be able to offer some suggestions. I realize there's not much concrete here, but some kind of "host concerns" endpoint on TC39's end might be useful.

**Comment by ljharb** [comment]
The discourse seems a reasonable place to discuss things that aren’t related to a specific repo.

**Comment by marcoscaceres** [comment]
Note that Discourse [might be going away](https://github.com/WICG/admin/issues/168), as it's not very well maintained... or, rather, we (WICG) haven't been doing a great job at maintaining our instance of it. 

This does remind me bit of the Back/Forward cache discussions that took place in the TAG:
https://github.com/w3ctag/design-reviews/issues/628

I wonder if this should follow a similar avenue and eventually end up as TAG API design guidance (and yeah, I know it affects TC39 specs also... but still... "Team Web"! 🫂)

**Comment by ljharb** [comment]
I’m talking about TC39’s discourse, which isn’t going anywhere.

**Comment by marcoscaceres** [comment]
oh, perfect! Thanks for clarifying @ljharb. 🙏 

Ok, let me know how y'all want to proceed. Perfectly happy to "do nothing" also if you think that's best.

**Comment by ajklein** [comment]
Note that this affects WebAssembly as well (see @dtig's https://github.com/WebAssembly/memory-control), and that solutions that might work for JS <-> Web APIs in isolation may be suboptimal when Wasm is also considered.

I don't know what that says for this repo, but just to caution that treating this as a TC39 + web APIs issue is not broad enough.

**Comment by annevk** [comment]
I guess that means we should be using this repository and people should be filing issues as they come across stuff...

**Comment by marcoscaceres** [comment]
Sounds good. Ok, Thanks for all the info everyone!
